apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: bob2606/hello-http:0.8.34
        name: hello-http
        env:
          - name: NODENAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        envFrom:
          - configMapRef:
              name: hello-env
        ports:
          - containerPort: 80
            name: http
        livenessProbe:
          httpGet:
            path: /livez
            port: 80
          periodSeconds: 5
          failureThreshold: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          periodSeconds: 2
          failureThreshold: 3
        volumeMounts:
          - name: status
            mountPath: /var/lib/hello-http
            subPath: hello

      volumes:
        - name: status
          nfs:
            server: 192.168.56.200
            path: /
