apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: version initiale
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy: {}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.29
        name: nginx
        env:
          - name: STAGE
            value: K8S
          - name: PODIP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: NB_JOURS
            valueFrom:
              configMapKeyRef:
                name: nginx-env
                key: JOURS
          - name: PASS
            valueFrom:
              secretKeyRef:
                name: nginx-pass
                key: PASSWORD
        readinessProbe:
          httpGet:
            path: /index.html
            port: 80
          periodSeconds: 4
          failureThreshold: 4
        livenessProbe:
          httpGet:
            path: /index.html
            port: 80
          periodSeconds: 10
          failureThreshold: 2
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
            readOnly: true

      volumes:
        - name: html
          hostPath:
            path: /home/stagiaire/data
            type: Directory
